#!/bin/bash

echo "=== CI/CD + Docker Hub + Production Setup Guide ==="
echo ""
echo "STEP 1: Configure GitHub Secrets"
echo "================================"
echo "Go to: Settings > Secrets and variables > Actions > New repository secret"
echo ""
echo "Add these secrets:"
echo "  • DOCKER_USERNAME     → Your Docker Hub username"
echo "  • DOCKER_PASSWORD     → Your Docker Hub access token (NOT password!)"
echo "  • DEPLOY_HOST         → Your production server IP/hostname"
echo "  • DEPLOY_USER         → SSH user (usually 'ubuntu' or 'ec2-user')"
echo "  • DEPLOY_KEY          → Private SSH key (cat ~/.ssh/id_rsa | base64)"
echo ""
echo "STEP 2: Create Docker Hub Access Token"
echo "======================================="
echo "1. Go to hub.docker.com"
echo "2. Account Settings > Security > New Access Token"
echo "3. Name it 'github-actions'"
echo "4. Copy and paste into DOCKER_PASSWORD secret"
echo ""
echo "STEP 3: Generate SSH Deploy Key"
echo "================================"
echo "On your local machine:"
echo "  ssh-keygen -t rsa -b 4096 -f ~/.ssh/deploy_key -N ''"
echo "  cat ~/.ssh/deploy_key | base64 -w 0"
echo ""
echo "On production server (~/.ssh/authorized_keys):"
echo "  cat ~/.ssh/deploy_key.pub >> ~/.ssh/authorized_keys"
echo ""
echo "STEP 4: Prepare Production Server"
echo "=================================="
echo "SSH into your server and run:"
echo "  curl -fsSL https://get.docker.com -o get-docker.sh"
echo "  sh get-docker.sh"
echo "  sudo usermod -aG docker \$USER"
echo "  mkdir -p /app && cd /app"
echo "  git clone <your-repo> ."
echo ""
echo "STEP 5: Deploy Locally (Testing)"
echo "================================"
echo "Test deployment script locally:"
echo "  chmod +x deploy.sh"
echo "  DOCKER_USERNAME=your_username DB_PASSWORD=secure_password ./deploy.sh"
echo ""
echo "STEP 6: Push to GitHub"
echo "====================="
echo "  git add ."
echo "  git commit -m 'Add CI/CD and production configs'"
echo "  git push origin main"
echo ""
echo "✓ CI/CD pipeline will trigger automatically!"
echo "✓ Check Actions tab for build/test results"
echo ""
echo "STEP 7: Monitor Production"
echo "=========================="
echo "View logs:"
echo "  docker compose -f docker-compose.prod.yml logs -f app"
echo ""
echo "Check status:"
echo "  docker compose -f docker-compose.prod.yml ps"
echo ""
echo "Scale app (if needed):"
echo "  docker compose -f docker-compose.prod.yml up -d --scale app=3"
